# используем язык java.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)